obj-y					+= common/
obj-$(CONFIG_PLAT_LINUX)		+= linux/
obj-$(CONFIG_PLAT_OSX)			+= osx/
obj-$(CONFIG_PLAT_WINDOWS)		+= windows/
obj-$(CONFIG_PLAT_DOS)			+= dos/
obj-$(CONFIG_NINTENDO_PPC_COMMON)	+= nintendo-ppc-common/
obj-$(CONFIG_PLAT_GCN)			+= gcn/
obj-$(CONFIG_PLAT_WII)			+= wii/
obj-$(CONFIG_PLAT_WIIU)			+= wiiu/
obj-$(CONFIG_PLAT_PS3)			+= ps3/
obj-$(CONFIG_PLAT_SWITCH)		+= switch/

